import React from 'react';
import ReactDOM from 'react-dom';

import fire from '../fire';

// -------> COMPONENTS
import Spinner from './spinner.js';

class MainUser extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            name: "",
            lastName: "",
            avatar: "",
            error: false,
            dataReady: false
        }
    }

    // function for getting random user info & avatar from API
    createUser = () => {
        const userUrl = "https://randomuser.me/api/";

        fetch(userUrl)
            .then(res => res.json()
            .then(res => {
                // console.log(res);
                const firstName = res.results[0].name.first;
                const lastName = res.results[0].name.last;
                const avatar = res.results[0].picture.large;
                const city = res.results[0].location.city;

                const randomUserProfile = {
                    name: firstName,
                    lastName: lastName,
                    avatar
                }

                // using google geocode api to get a formatted google adddres of the user based on the city name generated by random user API
                const geocodeUrl = `https://maps.googleapis.com/maps/api/geocode/json?address=${city}&key=AIzaSyBAyZk26RYvZXIvGHkLSohlKzZxwpXVqos`;
                fetch(geocodeUrl)
                    .then(res => res.json()
                    .then(res => {
                        // console.log(res.results[0].formatted_address);
                        const formattedAddress = res.results[0].formatted_address;
                        randomUserProfile.location = formattedAddress;
                        fire.database().ref('random_user').push(randomUserProfile);
                        this.setState({
                            location: formattedAddress
                        });
                    })

                )
                .catch((err) => {
                    this.setState ({
                        error: true
                    });
                })

                    this.setState({
                        name: res.results[0].name.first,
                        lastName: res.results[0].name.last,
                        avatar: res.results[0].picture.large,
                        dataReady: true
                    });
                }) )
            .catch((err) => {
                this.setState ({
                    error: true
                });
            })
    }


    componentDidMount() {
        this.createUser();
    }

    render() {
        const { name, lastName, avatar, location, dataReady } = this.state;

        return (
            <div>
                {
                    dataReady
                    ?
                    <div>
                        <figure className="main__users--avatar" style={{backgroundImage: `url(${avatar})`}}>
                        </figure>
                        <div className="main__users--info">
                            <p className="main__users--name">Name: <span className="main__users--bold">{name} {lastName}</span></p>
                            <p className="main__users--location">Location: <span className="main__users--bold">{location}</span></p>
                        </div>
                    </div>
                    : <Spinner />
                }
            </div>
        );
    }
}


export default MainUser;